CC = gcc

SRC_TREE = ../../

SRC_DIR = ${SRC_TREE}/src

INC_DIR = ${SRC_TREE}/include

CFLAGS = -g -Wall -iquote "${INC_DIR}" -D _LINUX_

all: liblmtx.dll

liblmtx.dll: lmtx.c
	$(CC) $(CFLAGS) -Wall -Wl,--export-all-symbols -shared -o liblmtx.dll $(SRC_DIR)/fs/unix/fs.o $(SRC_DIR)/interpreter/interp.o lmtx.c
	
clean:
	rm -rf *.o *.lo *.la *.dll .libs
