CC = gcc

SRC_TREE = ../../

SRC_DIR = ${SRC_TREE}/src

INC_DIR = ${SRC_TREE}/include

CFLAGS = -g -Wall -iquote "${INC_DIR}" -D _LINUX_

all: liblmtx.so

liblmtx.so: lmtx.c
	$(CC) $(CFLAGS) -Wall -export-dynamic -shared -fPIC -o liblmtx.so ../../src/interpreter/interp.c lmtx.c
	
clean:
	rm -rf *.o *.lo *.la *.so .libs
